install:
    - C:\Python27\Scripts\pip install networkx pydotplus nose

build: off

test_script:
    - C:\Python27\Scripts\nosetests test\
    - git clone --depth 1 --branch cppdep https://github.com/rakhimov/scram.git
    - cd scram
    - python ..\cppdep.py -f cppdep-win.xml
