language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - pypy
    - pypy3

os: linux

matrix:
    include:
        - os: osx
          language: generic

addons:
    apt:
        packages:
            - graphviz  # OS X takes forever via brew.

install:
    - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
        pip install nose;
      elif [[ "${TRAVIS_PYTHON_VERSION}" == "2.7" ]]; then
        export RUN_COVERAGE=true;
        pip install coverage codecov;
      fi &&
      pip install networkx pydotplus PyYAML PyKwalify

before_script:
    - git clone --depth 1 --branch cppdep https://github.com/rakhimov/scram.git

script:
    - if [[ $RUN_COVERAGE == true ]]; then
        cd scram &&
        nosetests -w ../ --with-coverage --cover-package=graph test/ &&
        coverage run --append --source=../ ../cppdep.py -c cppdep-ci.yml -l &&
        codecov;
      else
        nosetests test/ && cd scram && ../cppdep.py -c cppdep-ci.yml;
      fi &&
      if [[ ! "${TRAVIS_OS_NAME}" == "osx" ]]; then
        echo "Generating graph images from DOT.";
        dot -T pdf -O ./*.dot;
      fi
