language: python
python:
    - 2.7
    - 3.4
    - 3.5

install:
    - pip install networkx
    - pip install pydotplus
    - pip install coverage
    - pip install codecov

before_script:
    - git clone --branch cppdep https://github.com/rakhimov/scram.git

script:
    - coverage run ./networkx_ext.py
    - (cd scram && coverage run ../cppdep.py)  # TODO: coverage only for one build.
      # TODO: Run dot2any

after_success:
    - codecov > /dev/null  # TODO: Do this only in one single build.
