language: python
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - pypy
    - pypy3

os: linux

matrix:
    include:
        - os: osx
          language: generic

addons:
    apt:
        packages:
            - graphviz  # OS X takes forever via brew.

install:
    - pip install networkx
    - pip install pydotplus
    - pip install coverage
    - pip install codecov
    - pip install nose  # Not provided by default on OS X.

before_script:
    - git clone --depth 1 --branch cppdep https://github.com/rakhimov/scram.git

script:
    - nosetests --with-coverage test/
    - codecov
    - cd scram
    - coverage run --source=../ ../cppdep.py
    - codecov
    # Just convoluted if-then-else with ||, && only.
    - dot -T pdf -O ./*.dot || [[ -z $(which dot) ]]
