language: python
python:
    - 2.7
    - 3.4
    - 3.5

install:
    - pip install networkx
    - pip install pydotplus
    - pip install codecov

before_script:
    - git clone --branch cppdep https://github.com/rakhimov/scram.git

script:
    - ./networkx_ext.py
    - (cd scram && ../cppdep.py)
      # TODO: Run dot2any

after_success:
    - codecov > /dev/null  # TODO: Do this only in one single build.
