language: python
python:
    - 2.7
    - 3.4
    - 3.5

install:
    - pip install networkx
    - pip install pydotplus
    - pip install coverage
    - pip install codecov
    - sudo apt-get install graphviz

before_script:
    - git clone --depth 1 --branch cppdep https://github.com/rakhimov/scram.git
    - which dot

script:
    - coverage run ./networkx_ext.py
    - codecov
    - cd scram
    - coverage run --source=../ ../cppdep.py
    - codecov
    - coverage run --source=../ ../dot2any.py ./
    - codecov
    - cd ..
